"""Constants for the secret_santa package."""

TWILIO_ACCOUNT_SID = "TWILIO_ACCOUNT_SID"
TWILIO_AUTH_TOKEN = "TWILIO_AUTH_TOKEN"
TWILIO_NUMBER = "TWILIO_NUMBER"

MINIMUM_NUMBER_OF_PARTICIPANTS = 3

ENCODING = "utf-8"
